### ISSUE TITLE
Usage ?

### ISSUE THREAD

**Issue by acmoune** [theleagueof/ostrich-sans#13]
I am unable to use the different styles and weight, maybe you assume your consumers should have some degree of knowledge... you did not provide any usage guide, for newbies. 
I need to use ROUNDED and HEAVY. How should I proceed please ?

```
font-family: 'Ostrich Sans';
font-style: 'rounded';
font-weight: 'heavy';
```

This is not working.
please help.

Thanks in advance.

**Comment by acmoune** [comment]
OK, I finally got it, font-style is normal, then font weight can be 900, 700, 400, ...

**Comment by sursly** [comment]
Sorry! Just seeing this now. Yes that whole Ostrich Family could use some love, but thanks for letting us know.
