### ISSUE TITLE
Artifact in black K

### ISSUE THREAD

**Issue by markovandooren** [theleagueof/ostrich-sans#3]
Hi,

First of all, thank you for making this beautiful font open source. I was just using it in the black style, and noticed a (small) artifact in the K. The top leg of the K protrudes a tiny bit past the vertical. A screenshot is attached. 
![Screen Shot 2013-01-05 at 23 04 49](https://f.cloud.github.com/assets/3195129/45435/3072e2f6-5784-11e2-9136-0e30a05194cd.png)

**Comment by sursly** [comment]
OK. this should be resolved with the latest version of Ostrich Black.
