### ISSUE TITLE
Font bleeds together in Firefox

### ISSUE THREAD

**Issue by ghost** [theleagueof/ostrich-sans#5]
Is this a problem for anyone else?

http://i.imgur.com/JztvgKb.jpg

Looks fine in every other browser except Firefox. Using latest release.

**Comment by sursly** [comment]
Hey this doesn't look like a problem with ostrich but just your CSS. I've seen this happen with a "faux" bold effect. If you're using Ostrich via @font-face as a heading, be sure to set it to font-weight: normal; That should fix what you see. Webkit is slightly smarter about it.
